### PR TITLE
BC BREAKING: Revert "Add support for rpc encoded wsdl"

### LINKED ISSUE #99: Different xml output since wasabi 3.6 update
Thank you for your time and this gem.
We are using the wasabi (3.6.1) gem via the savon (2.12.1) gem.

With wasabi 3.6.1 we get a different xml output.

wasabi 3.5.0
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://servlets.iex.jv.com/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <tns:mergeToXML>
      <username>user</username>
      <inputDocument>
        <item>
          <data>JVBER ...JUVPRgo=</data>
          <filename>max-mustermann.pdf</filename>
        </item>
      </inputDocument>
    </tns:mergeToXML>
  </env:Body>
</env:Envelope>
```

wasabi 3.6.1
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://servlets.iex.jv.com/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <mergeToXML>
      <username xsi:type="xsd:string">user</username>
      <inputDocument xsi:type="tns:inputDocArray">[{:item=&gt;{:data=&gt;"JVBER...JUVPRgo=\n", :filename=&gt;"max-mustermann.pdf"}}]</inputDocument>
    </mergeToXML>
  </env:Body>
</env:Envelope>
```

If we remove this block the XML is like the XML from wasabi 3.5.0.
https://github.com/savonrb/wasabi/compare/v3.5.0..v3.6.1#diff-7c3adc3042c46c5df567b221e60c3442R285

This block comes from this commit:
https://github.com/savonrb/wasabi/commit/8b18d4e70c11a0774af02ce165d9358b2311e88a

The .wsdl File looks like this:
```
<message name="mergeToXML">
<part name="username" type="xsd:string"/>
<part name="inputDocument" type="tns:inputDocArray"/>
</message>
```

Is there a Problem with the .wsdl File or the commit or savon?
Thank you in advance.

### PR DESCRIPTION
**Pull request by fsateler**
This change breaks backwards compatibility, by changing the parsing of
the SOAP messages. The fact that existing tests needed to be changed,
shows that the semantics did change.

I do not know if the change is incorrect. But if introduced, according
to SemVer it must be introduced in a new major release, to give
downstreams the chance to port their code accordingly.

Fixes #99

See also https://github.com/savonrb/savon/issues/935

This reverts commit 6fc97c6048b28aa79d053dc7bf9b736513c42c11.

cc @fernandes @tjarratt

### CODE REVIEW

**Comment by fernandes** [comment]
hey @fsateler , sorry if it caused any trouble, I was working on a project using savon/wasabi a few years ago and this was (apparently) the fix... as you are using it nowadays and it became a trouble, I'm +1 to merge the fix, I'm still not working on that project anymore, so I can't test this PR

thanks for mentioning me!

**Comment by fsateler** [comment]
Hi! Friendly ping. Is there anything I can do to help move this forward?

**Comment by olleolleolle** [comment]
So, this drops a block of code and the tests still pass. That's suspicious, of course, suspicion about the old code, that is. 

The PR description is a little short and does not go into detail about the benefits we get now - that would always help a reviewer. 

I agree that we have troublesome parts in current Wasabi and want to work on getting that fixed. Users pin to earlier releases to make their apps work.

I'll reread all the linked issues.

**Comment by olleolleolle** [comment]
@fsateler Ah, thanks! Now back on track and ready to merge!

**Comment by olleolleolle** [comment]
@fsateler Thanks for fixing this!

**Comment by fsateler** [comment]
@olleolleolle thanks to you for maintaining this gem!

**Comment by arashm** [comment]
Thanks @olleolleolle and @fsateler. Is there any plan to release a new version on rubygems any time soon?

**Comment by olleolleolle** [comment]
Soon is a strong word. Maybe within a month when I'm back home?

**Comment by olleolleolle** [comment]
The current release can be used with a git source in Gemfiles, adding robustness to the testedness in the real world, for this upcoming version.

**Comment by arashm** [comment]
Hey @olleolleolle, sorry for insisting on this, but got the time to release the new version?

**Pull request merged**
